### PR TITLE
change(browser terminal): overwrite ClientOptions with url query params

### PR DESCRIPTION
**Pull request by cangzhang**
https://github.com/tsl0922/ttyd/issues/1270

This PR enables ttyd to read ClientOption settings from url and overwrite server configuration.

Here is a working demo:

https://github.com/tsl0922/ttyd/assets/1357073/ff17e8b5-ac72-4760-9f98-cc590cdb29be

### CODE REVIEW

**Comment by tsl0922** [comment]
The value defined in `App.tsx` is default value, it can still be overrided by [Client Options](https://github.com/tsl0922/ttyd/wiki/Client-Options) from the server side.

**Comment by cangzhang** [comment]
Update:
- Added support for the following options:
	- disableLeaveAlert
	- disableResizeOverlay
	- disableReconnect
	- enableZmodem
	- enableTrzsz
	- enableSixel
	- unicodeVersion
	- rendererType

**Comment by cangzhang** [comment]
Updated. plz have a look

**Comment by tsl0922** [comment]
Merged manually.

**Pull request closed without merging**
