### PR TITLE
Disable WebGL2 on Safari and iOS

### PR DESCRIPTION
**Pull request by mdevaev**
Fixes: tsl0922/ttyd#780
Fixes: tsl0922/ttyd#798

This patch is similar to tsl0922/ttyd#785 but with a correct Safari detection code

### CODE REVIEW

**Comment by mdevaev** [comment]
Improved for iOS

**Comment by mdevaev** [comment]
Note: Works on iPhone, but may not work on iPad

**Comment by mdevaev** [comment]
The latest ios versions have changed the behavior, so the iseos verification code needs to be finalized, I will do it

**Comment by tsl0922** [comment]
I believe this is broken on macOS Safari 15.0 too, so you can just detect Safari.

There's already a workaround at xtermjs/xterm.js#3500 but not released yet, we should add a try catch when enabling webgl addon for next xterm.js version.

**Comment by mdevaev** [comment]
@tsl0922 ping?

**Pull request merged**
