### PR TITLE
Add Authorization header as an env var

### PR DESCRIPTION
**Pull request by rchernobelskiy**
Passing the Authorization header to the subprocess in an env var, allowing custom auth to work when deployed behind reverse proxies with auth logic
Tag for related issues (https://github.com/tsl0922/ttyd/issues/108, https://github.com/tsl0922/ttyd/issues/364, https://github.com/tsl0922/ttyd/issues/274)

### CODE REVIEW

**Comment by rchernobelskiy** [comment]
Hi @tsl0922, curious if you have any thoughts/feedback on this one

**Comment by tsl0922** [comment]
Sorry, I didn't have time to come up with a good design for it, so I'm leaving this PR open. If you really want it get merged soon, add a command line option for it, and do not enabled it by default.

**Comment by JeremiahDJordan** [comment]
Implemented here:
https://github.com/tsl0922/ttyd/wiki/Auth-Proxy
https://github.com/tsl0922/ttyd/commit/e402edf13cb14d9ba09169a490dbd489853cfa92

**Comment by rchernobelskiy** [comment]
> Implemented here: https://github.com/tsl0922/ttyd/wiki/Auth-Proxy [e402edf](https://github.com/tsl0922/ttyd/commit/e402edf13cb14d9ba09169a490dbd489853cfa92)

Cool, though don't think that passes it to the process via env var or otherwise

**Pull request closed without merging**
